### ISSUE TITLE
arith/Logical/Assignment operators need isOperator functions of their own

### ISSUE THREAD

**Issue by piercecunneen** [zachjanicki/javascript_interpreter#1]
Right now, we only have regex test functions for isOperator. However, these don't cover all of the operator types (logical, assignment, and arithmetic).

I see two options. 

1) We ditch isOperator and have three separate functions (isArithOperator, isLogicalOperator, and isAssignmentOperator) that determine which operator is which. 

2) We keep isOperator, that will help us determine that a string is an operator Token, and then in our function that parses strings into operators we first call isOperator and then once we know the string is an operator we then determine which specific operator it is. 

Option 2) might have better runtime on average, since we don't run the three isOperator functions every time, but honestly shouldn't be that big of a deal either way

**Comment by zachjanicki** [comment]
Going to go with option one, at least for right now. It will be simpler to write. If it really causes any actual issues, I will change it to option two later on
